version: '3.4'

services:
  # MongoDB service
  mongo_db:
    container_name: mongodb
    image: mongo:5.0
    restart: unless-stopped
    volumes:
      - newdb:/data/db
    networks:
      - hmsbackend_default

  # HMS Service 1
  hmsservicesone:
    container_name: hmsservicesone
    restart: unless-stopped
    build: .
    ports:
      - 5003:5000
    environment:
      PORT: 5000
      DOCKERDATABASE: mongodb://mongo_db:27017/hms
      KEYGEN: 'w{v{<J2e&$x[/<V#&#G:?Ti?Frv+-P'
    networks:
      - hmsbackend_default
    volumes:
      - ./uploads:/app/uploads
      #- ./errorlogs:/app/errorlogs
    depends_on:
      - mongo_db

  # HMS Service 2
  hmsservicestwo:
    container_name: hmsservicestwo
    restart: unless-stopped
    build: .
    ports:
      - 5001:5000
    environment:
      PORT: 5000
      DOCKERDATABASE: mongodb://mongo_db:27017/hms
      KEYGEN: 'w{v{<J2e&$x[/<V#&#G:?Ti?Frv+-P'
    networks:
      - hmsbackend_default
    volumes:
      - ./uploads:/app/uploads
      #- ./errorlogs:/app/errorlogs
    depends_on:
      - mongo_db

  # HMS Service 3
  hmsservicesthree:
    container_name: hmsservicesthree
    restart: unless-stopped
    build: .
    ports:
      - 5002:5000
    environment:
      PORT: 5000
      DOCKERDATABASE: mongodb://mongo_db:27017/hms
      KEYGEN: 'w{v{<J2e&$x[/<V#&#G:?Ti?Frv+-P'
    networks:
      - hmsbackend_default
    volumes:
      - ./uploads:/app/uploads
      #- ./errorlogs:/app/errorlogs
    depends_on:
      - mongo_db

# Volumes
volumes:
  newdb:

# Networks
networks:
  hmsbackend_default:
    driver: bridge
